language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt -- --check
  - cargo clippy --all -- -D warnings
